development:
  adapter: postgresql
  encoding: unicode
  database: discourse_dev
  username: postgres
  password: postgres
  host: localhost
  pool: 5


demo_test:
  adapter: postgresql
  encoding: unicode
  database: discourse_development
  username: postgres
  password: rfo2vitodiscourse
  host: localhost
  pool: 5

profile:
  adapter: postgresql
  encoding: unicode
  database: discourse_development
  username: postgres
  password: rfo2vitodiscourse
  host: localhost
  pool: 5