development:
  adapter: postgresql
  encoding: unicode
  database: discourse_development
  username: postgres
  password: postgres
  host: localhost
  pool: 5

profile:
  adapter: postgresql
  encoding: unicode
  database: discourse_development
  username: postgres
  password: rfo2vitodiscourse
  host: 95.85.63.95
  pool: 25